# 伺服器埠號
quarkus.http.port=8080

# --- 資料庫連線設定 ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.reactive.url=postgresql://localhost:5432/seckill

# --- Hibernate 設定 ---
# 自動建立或刪除資料表
quarkus.hibernate-orm.database.generation=drop-and-create 
# 控制台印出 SQL
quarkus.hibernate-orm.log.sql=true

# --- Redis 連線設定 ---
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.max-pool-size=20
quarkus.redis.max-pool-waiting=500

# 暫時關閉 Quarkus 的自動啟動 Docker 功能
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.redis.devservices.enabled=false

# --- 監控設定 ---
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
